### PR TITLE
Many updates to make it more like canopy's dsl

### PR DESCRIPTION
**Pull request by lefthandedgoat**
Remove the sleeps in click so that we can push reliability into the right places (never had any reliability problems)
Refactor away from a DU for selectors and instead go with strings that are converted to Selenium.By which is what selenium uses to get stuff and is 'universal' and makes thing more extensible.
Added some assertions

Look and feel of the DSL is more more like canopy now.

Set a pattern for adding more assertsion like != and notDisplayed etc

### CODE REVIEW

**Comment by forki** [comment]
image

but we will solve this...

**Comment by lefthandedgoat** [comment]
Hm can you try with the emulator loaded?  And do you have Intel HAXM isntalled (it makes things fast).

I am unsure if its related to how fast the app is loading and the emulator running or something else.

**Comment by forki** [comment]
Yes usually things work when the emulator is started Mano. But that does not help with CI

**Comment by lefthandedgoat** [comment]
Ok there is probably some thing you can key off of that tells you everything is loaded properly.  Just gotta figure out what it is

**Comment by forki** [comment]
I assume it's at the end of a test. Maybe we need to wait until the app is shut down.

**Pull request merged**
